# Вызначаем вашы публічныя ключы (гэтак жа, як у secrets.nix)
[identities]
koshchei = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINh45udLj81NiAX+8c9LsVL3wfTfIMjbCmgxXADVDgcS"

# Звязваем файлы сакрэтаў з гэтымі ключамі
[[paths]]
glob = "secrets/*.age"
identities = ["koshchei"]

[secrets.gdrive-token]
path = "secrets/gdrive-token.age"
keys = ["age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
